<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Version>0.2.1</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <Authors>NickYCLin</Authors>
    <Copyright>Copyright © 2026 NickYCLin</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/NickYCLin/exe-blueprint</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
