namespace ExeBlueprint.Analysis;

// 名稱取自 dotnet/wpf v10.0.11 的 WpfGeneratedKnownTypes.cs 與 WpfGeneratedKnownProperties.cs。
// 只保存 BAML ID 對應名稱，不參考或載入 WPF runtime assembly。
// Source commit: 6e295c0c870baf4c02897e89d53e2f3e4a6aeba5 (MIT, .NET Foundation and contributors)
internal static class WpfBamlKnownIds
{
    private static readonly string?[] TypeNames =
    [
        null,
        "AccessText",
        "AdornedElementPlaceholder",
        "Adorner",
        "AdornerDecorator",
        "AdornerLayer",
        "AffineTransform3D",
        "AmbientLight",
        "AnchoredBlock",
        "Animatable",
        "AnimationClock",
        "AnimationTimeline",
        "Application",
        "ArcSegment",
        "ArrayExtension",
        "AxisAngleRotation3D",
        "BaseIListConverter",
        "BeginStoryboard",
        "BevelBitmapEffect",
        "BezierSegment",
        "Binding",
        "BindingBase",
        "BindingExpression",
        "BindingExpressionBase",
        "BindingListCollectionView",
        "BitmapDecoder",
        "BitmapEffect",
        "BitmapEffectCollection",
        "BitmapEffectGroup",
        "BitmapEffectInput",
        "BitmapEncoder",
        "BitmapFrame",
        "BitmapImage",
        "BitmapMetadata",
        "BitmapPalette",
        "BitmapSource",
        "Block",
        "BlockUIContainer",
        "BlurBitmapEffect",
        "BmpBitmapDecoder",
        "BmpBitmapEncoder",
        "Bold",
        "BoolIListConverter",
        "Boolean",
        "BooleanAnimationBase",
        "BooleanAnimationUsingKeyFrames",
        "BooleanConverter",
        "BooleanKeyFrame",
        "BooleanKeyFrameCollection",
        "BooleanToVisibilityConverter",
        "Border",
        "BorderGapMaskConverter",
        "Brush",
        "BrushConverter",
        "BulletDecorator",
        "Button",
        "ButtonBase",
        "Byte",
        "ByteAnimation",
        "ByteAnimationBase",
        "ByteAnimationUsingKeyFrames",
        "ByteConverter",
        "ByteKeyFrame",
        "ByteKeyFrameCollection",
        "CachedBitmap",
        "Camera",
        "Canvas",
        "Char",
        "CharAnimationBase",
        "CharAnimationUsingKeyFrames",
        "CharConverter",
        "CharIListConverter",
        "CharKeyFrame",
        "CharKeyFrameCollection",
        "CheckBox",
        "Clock",
        "ClockController",
        "ClockGroup",
        "CollectionContainer",
        "CollectionView",
        "CollectionViewSource",
        "Color",
        "ColorAnimation",
        "ColorAnimationBase",
        "ColorAnimationUsingKeyFrames",
        "ColorConvertedBitmap",
        "ColorConvertedBitmapExtension",
        "ColorConverter",
        "ColorKeyFrame",
        "ColorKeyFrameCollection",
        "ColumnDefinition",
        "CombinedGeometry",
        "ComboBox",
        "ComboBoxItem",
        "CommandConverter",
        "ComponentResourceKey",
        "ComponentResourceKeyConverter",
        "CompositionTarget",
        "Condition",
        "ContainerVisual",
        "ContentControl",
        "ContentElement",
        "ContentPresenter",
        "ContentPropertyAttribute",
        "ContentWrapperAttribute",
        "ContextMenu",
        "ContextMenuService",
        "Control",
        "ControlTemplate",
        "ControllableStoryboardAction",
        "CornerRadius",
        "CornerRadiusConverter",
        "CroppedBitmap",
        "CultureInfo",
        "CultureInfoConverter",
        "CultureInfoIetfLanguageTagConverter",
        "Cursor",
        "CursorConverter",
        "DashStyle",
        "DataChangedEventManager",
        "DataTemplate",
        "DataTemplateKey",
        "DataTrigger",
        "DateTime",
        "DateTimeConverter",
        "DateTimeConverter2",
        "Decimal",
        "DecimalAnimation",
        "DecimalAnimationBase",
        "DecimalAnimationUsingKeyFrames",
        "DecimalConverter",
        "DecimalKeyFrame",
        "DecimalKeyFrameCollection",
        "Decorator",
        "DefinitionBase",
        "DependencyObject",
        "DependencyProperty",
        "DependencyPropertyConverter",
        "DialogResultConverter",
        "DiffuseMaterial",
        "DirectionalLight",
        "DiscreteBooleanKeyFrame",
        "DiscreteByteKeyFrame",
        "DiscreteCharKeyFrame",
        "DiscreteColorKeyFrame",
        "DiscreteDecimalKeyFrame",
        "DiscreteDoubleKeyFrame",
        "DiscreteInt16KeyFrame",
        "DiscreteInt32KeyFrame",
        "DiscreteInt64KeyFrame",
        "DiscreteMatrixKeyFrame",
        "DiscreteObjectKeyFrame",
        "DiscretePoint3DKeyFrame",
        "DiscretePointKeyFrame",
        "DiscreteQuaternionKeyFrame",
        "DiscreteRectKeyFrame",
        "DiscreteRotation3DKeyFrame",
        "DiscreteSingleKeyFrame",
        "DiscreteSizeKeyFrame",
        "DiscreteStringKeyFrame",
        "DiscreteThicknessKeyFrame",
        "DiscreteVector3DKeyFrame",
        "DiscreteVectorKeyFrame",
        "DockPanel",
        "DocumentPageView",
        "DocumentReference",
        "DocumentViewer",
        "DocumentViewerBase",
        "Double",
        "DoubleAnimation",
        "DoubleAnimationBase",
        "DoubleAnimationUsingKeyFrames",
        "DoubleAnimationUsingPath",
        "DoubleCollection",
        "DoubleCollectionConverter",
        "DoubleConverter",
        "DoubleIListConverter",
        "DoubleKeyFrame",
        "DoubleKeyFrameCollection",
        "Drawing",
        "DrawingBrush",
        "DrawingCollection",
        "DrawingContext",
        "DrawingGroup",
        "DrawingImage",
        "DrawingVisual",
        "DropShadowBitmapEffect",
        "Duration",
        "DurationConverter",
        "DynamicResourceExtension",
        "DynamicResourceExtensionConverter",
        "Ellipse",
        "EllipseGeometry",
        "EmbossBitmapEffect",
        "EmissiveMaterial",
        "EnumConverter",
        "EventManager",
        "EventSetter",
        "EventTrigger",
        "Expander",
        "Expression",
        "ExpressionConverter",
        "Figure",
        "FigureLength",
        "FigureLengthConverter",
        "FixedDocument",
        "FixedDocumentSequence",
        "FixedPage",
        "Floater",
        "FlowDocument",
        "FlowDocumentPageViewer",
        "FlowDocumentReader",
        "FlowDocumentScrollViewer",
        "FocusManager",
        "FontFamily",
        "FontFamilyConverter",
        "FontSizeConverter",
        "FontStretch",
        "FontStretchConverter",
        "FontStyle",
        "FontStyleConverter",
        "FontWeight",
        "FontWeightConverter",
        "FormatConvertedBitmap",
        "Frame",
        "FrameworkContentElement",
        "FrameworkElement",
        "FrameworkElementFactory",
        "FrameworkPropertyMetadata",
        "FrameworkPropertyMetadataOptions",
        "FrameworkRichTextComposition",
        "FrameworkTemplate",
        "FrameworkTextComposition",
        "Freezable",
        "GeneralTransform",
        "GeneralTransformCollection",
        "GeneralTransformGroup",
        "Geometry",
        "Geometry3D",
        "GeometryCollection",
        "GeometryConverter",
        "GeometryDrawing",
        "GeometryGroup",
        "GeometryModel3D",
        "GestureRecognizer",
        "GifBitmapDecoder",
        "GifBitmapEncoder",
        "GlyphRun",
        "GlyphRunDrawing",
        "GlyphTypeface",
        "Glyphs",
        "GradientBrush",
        "GradientStop",
        "GradientStopCollection",
        "Grid",
        "GridLength",
        "GridLengthConverter",
        "GridSplitter",
        "GridView",
        "GridViewColumn",
        "GridViewColumnHeader",
        "GridViewHeaderRowPresenter",
        "GridViewRowPresenter",
        "GridViewRowPresenterBase",
        "GroupBox",
        "GroupItem",
        "Guid",
        "GuidConverter",
        "GuidelineSet",
        "HeaderedContentControl",
        "HeaderedItemsControl",
        "HierarchicalDataTemplate",
        "HostVisual",
        "Hyperlink",
        "IAddChild",
        "IAddChildInternal",
        "ICommand",
        "IComponentConnector",
        "INameScope",
        "IStyleConnector",
        "IconBitmapDecoder",
        "Image",
        "ImageBrush",
        "ImageDrawing",
        "ImageMetadata",
        "ImageSource",
        "ImageSourceConverter",
        "InPlaceBitmapMetadataWriter",
        "InkCanvas",
        "InkPresenter",
        "Inline",
        "InlineCollection",
        "InlineUIContainer",
        "InputBinding",
        "InputDevice",
        "InputLanguageManager",
        "InputManager",
        "InputMethod",
        "InputScope",
        "InputScopeConverter",
        "InputScopeName",
        "InputScopeNameConverter",
        "Int16",
        "Int16Animation",
        "Int16AnimationBase",
        "Int16AnimationUsingKeyFrames",
        "Int16Converter",
        "Int16KeyFrame",
        "Int16KeyFrameCollection",
        "Int32",
        "Int32Animation",
        "Int32AnimationBase",
        "Int32AnimationUsingKeyFrames",
        "Int32Collection",
        "Int32CollectionConverter",
        "Int32Converter",
        "Int32KeyFrame",
        "Int32KeyFrameCollection",
        "Int32Rect",
        "Int32RectConverter",
        "Int64",
        "Int64Animation",
        "Int64AnimationBase",
        "Int64AnimationUsingKeyFrames",
        "Int64Converter",
        "Int64KeyFrame",
        "Int64KeyFrameCollection",
        "Italic",
        "ItemCollection",
        "ItemsControl",
        "ItemsPanelTemplate",
        "ItemsPresenter",
        "JournalEntry",
        "JournalEntryListConverter",
        "JournalEntryUnifiedViewConverter",
        "JpegBitmapDecoder",
        "JpegBitmapEncoder",
        "KeyBinding",
        "KeyConverter",
        "KeyGesture",
        "KeyGestureConverter",
        "KeySpline",
        "KeySplineConverter",
        "KeyTime",
        "KeyTimeConverter",
        "KeyboardDevice",
        "Label",
        "LateBoundBitmapDecoder",
        "LengthConverter",
        "Light",
        "Line",
        "LineBreak",
        "LineGeometry",
        "LineSegment",
        "LinearByteKeyFrame",
        "LinearColorKeyFrame",
        "LinearDecimalKeyFrame",
        "LinearDoubleKeyFrame",
        "LinearGradientBrush",
        "LinearInt16KeyFrame",
        "LinearInt32KeyFrame",
        "LinearInt64KeyFrame",
        "LinearPoint3DKeyFrame",
        "LinearPointKeyFrame",
        "LinearQuaternionKeyFrame",
        "LinearRectKeyFrame",
        "LinearRotation3DKeyFrame",
        "LinearSingleKeyFrame",
        "LinearSizeKeyFrame",
        "LinearThicknessKeyFrame",
        "LinearVector3DKeyFrame",
        "LinearVectorKeyFrame",
        "List",
        "ListBox",
        "ListBoxItem",
        "ListCollectionView",
        "ListItem",
        "ListView",
        "ListViewItem",
        "Localization",
        "LostFocusEventManager",
        "MarkupExtension",
        "Material",
        "MaterialCollection",
        "MaterialGroup",
        "Matrix",
        "Matrix3D",
        "Matrix3DConverter",
        "MatrixAnimationBase",
        "MatrixAnimationUsingKeyFrames",
        "MatrixAnimationUsingPath",
        "MatrixCamera",
        "MatrixConverter",
        "MatrixKeyFrame",
        "MatrixKeyFrameCollection",
        "MatrixTransform",
        "MatrixTransform3D",
        "MediaClock",
        "MediaElement",
        "MediaPlayer",
        "MediaTimeline",
        "Menu",
        "MenuBase",
        "MenuItem",
        "MenuScrollingVisibilityConverter",
        "MeshGeometry3D",
        "Model3D",
        "Model3DCollection",
        "Model3DGroup",
        "ModelVisual3D",
        "ModifierKeysConverter",
        "MouseActionConverter",
        "MouseBinding",
        "MouseDevice",
        "MouseGesture",
        "MouseGestureConverter",
        "MultiBinding",
        "MultiBindingExpression",
        "MultiDataTrigger",
        "MultiTrigger",
        "NameScope",
        "NavigationWindow",
        "NullExtension",
        "NullableBoolConverter",
        "NullableConverter",
        "NumberSubstitution",
        "Object",
        "ObjectAnimationBase",
        "ObjectAnimationUsingKeyFrames",
        "ObjectDataProvider",
        "ObjectKeyFrame",
        "ObjectKeyFrameCollection",
        "OrthographicCamera",
        "OuterGlowBitmapEffect",
        "Page",
        "PageContent",
        "PageFunctionBase",
        "Panel",
        "Paragraph",
        "ParallelTimeline",
        "ParserContext",
        "PasswordBox",
        "Path",
        "PathFigure",
        "PathFigureCollection",
        "PathFigureCollectionConverter",
        "PathGeometry",
        "PathSegment",
        "PathSegmentCollection",
        "PauseStoryboard",
        "Pen",
        "PerspectiveCamera",
        "PixelFormat",
        "PixelFormatConverter",
        "PngBitmapDecoder",
        "PngBitmapEncoder",
        "Point",
        "Point3D",
        "Point3DAnimation",
        "Point3DAnimationBase",
        "Point3DAnimationUsingKeyFrames",
        "Point3DCollection",
        "Point3DCollectionConverter",
        "Point3DConverter",
        "Point3DKeyFrame",
        "Point3DKeyFrameCollection",
        "Point4D",
        "Point4DConverter",
        "PointAnimation",
        "PointAnimationBase",
        "PointAnimationUsingKeyFrames",
        "PointAnimationUsingPath",
        "PointCollection",
        "PointCollectionConverter",
        "PointConverter",
        "PointIListConverter",
        "PointKeyFrame",
        "PointKeyFrameCollection",
        "PointLight",
        "PointLightBase",
        "PolyBezierSegment",
        "PolyLineSegment",
        "PolyQuadraticBezierSegment",
        "Polygon",
        "Polyline",
        "Popup",
        "PresentationSource",
        "PriorityBinding",
        "PriorityBindingExpression",
        "ProgressBar",
        "ProjectionCamera",
        "PropertyPath",
        "PropertyPathConverter",
        "QuadraticBezierSegment",
        "Quaternion",
        "QuaternionAnimation",
        "QuaternionAnimationBase",
        "QuaternionAnimationUsingKeyFrames",
        "QuaternionConverter",
        "QuaternionKeyFrame",
        "QuaternionKeyFrameCollection",
        "QuaternionRotation3D",
        "RadialGradientBrush",
        "RadioButton",
        "RangeBase",
        "Rect",
        "Rect3D",
        "Rect3DConverter",
        "RectAnimation",
        "RectAnimationBase",
        "RectAnimationUsingKeyFrames",
        "RectConverter",
        "RectKeyFrame",
        "RectKeyFrameCollection",
        "Rectangle",
        "RectangleGeometry",
        "RelativeSource",
        "RemoveStoryboard",
        "RenderOptions",
        "RenderTargetBitmap",
        "RepeatBehavior",
        "RepeatBehaviorConverter",
        "RepeatButton",
        "ResizeGrip",
        "ResourceDictionary",
        "ResourceKey",
        "ResumeStoryboard",
        "RichTextBox",
        "RotateTransform",
        "RotateTransform3D",
        "Rotation3D",
        "Rotation3DAnimation",
        "Rotation3DAnimationBase",
        "Rotation3DAnimationUsingKeyFrames",
        "Rotation3DKeyFrame",
        "Rotation3DKeyFrameCollection",
        "RoutedCommand",
        "RoutedEvent",
        "RoutedEventConverter",
        "RoutedUICommand",
        "RoutingStrategy",
        "RowDefinition",
        "Run",
        "RuntimeNamePropertyAttribute",
        "SByte",
        "SByteConverter",
        "ScaleTransform",
        "ScaleTransform3D",
        "ScrollBar",
        "ScrollContentPresenter",
        "ScrollViewer",
        "Section",
        "SeekStoryboard",
        "Selector",
        "Separator",
        "SetStoryboardSpeedRatio",
        "Setter",
        "SetterBase",
        "Shape",
        "Single",
        "SingleAnimation",
        "SingleAnimationBase",
        "SingleAnimationUsingKeyFrames",
        "SingleConverter",
        "SingleKeyFrame",
        "SingleKeyFrameCollection",
        "Size",
        "Size3D",
        "Size3DConverter",
        "SizeAnimation",
        "SizeAnimationBase",
        "SizeAnimationUsingKeyFrames",
        "SizeConverter",
        "SizeKeyFrame",
        "SizeKeyFrameCollection",
        "SkewTransform",
        "SkipStoryboardToFill",
        "Slider",
        "SolidColorBrush",
        "SoundPlayerAction",
        "Span",
        "SpecularMaterial",
        "SpellCheck",
        "SplineByteKeyFrame",
        "SplineColorKeyFrame",
        "SplineDecimalKeyFrame",
        "SplineDoubleKeyFrame",
        "SplineInt16KeyFrame",
        "SplineInt32KeyFrame",
        "SplineInt64KeyFrame",
        "SplinePoint3DKeyFrame",
        "SplinePointKeyFrame",
        "SplineQuaternionKeyFrame",
        "SplineRectKeyFrame",
        "SplineRotation3DKeyFrame",
        "SplineSingleKeyFrame",
        "SplineSizeKeyFrame",
        "SplineThicknessKeyFrame",
        "SplineVector3DKeyFrame",
        "SplineVectorKeyFrame",
        "SpotLight",
        "StackPanel",
        "StaticExtension",
        "StaticResourceExtension",
        "StatusBar",
        "StatusBarItem",
        "StickyNoteControl",
        "StopStoryboard",
        "Storyboard",
        "StreamGeometry",
        "StreamGeometryContext",
        "StreamResourceInfo",
        "String",
        "StringAnimationBase",
        "StringAnimationUsingKeyFrames",
        "StringConverter",
        "StringKeyFrame",
        "StringKeyFrameCollection",
        "StrokeCollection",
        "StrokeCollectionConverter",
        "Style",
        "Stylus",
        "StylusDevice",
        "TabControl",
        "TabItem",
        "TabPanel",
        "Table",
        "TableCell",
        "TableColumn",
        "TableRow",
        "TableRowGroup",
        "TabletDevice",
        "TemplateBindingExpression",
        "TemplateBindingExpressionConverter",
        "TemplateBindingExtension",
        "TemplateBindingExtensionConverter",
        "TemplateKey",
        "TemplateKeyConverter",
        "TextBlock",
        "TextBox",
        "TextBoxBase",
        "TextComposition",
        "TextCompositionManager",
        "TextDecoration",
        "TextDecorationCollection",
        "TextDecorationCollectionConverter",
        "TextEffect",
        "TextEffectCollection",
        "TextElement",
        "TextSearch",
        "ThemeDictionaryExtension",
        "Thickness",
        "ThicknessAnimation",
        "ThicknessAnimationBase",
        "ThicknessAnimationUsingKeyFrames",
        "ThicknessConverter",
        "ThicknessKeyFrame",
        "ThicknessKeyFrameCollection",
        "Thumb",
        "TickBar",
        "TiffBitmapDecoder",
        "TiffBitmapEncoder",
        "TileBrush",
        "TimeSpan",
        "TimeSpanConverter",
        "Timeline",
        "TimelineCollection",
        "TimelineGroup",
        "ToggleButton",
        "ToolBar",
        "ToolBarOverflowPanel",
        "ToolBarPanel",
        "ToolBarTray",
        "ToolTip",
        "ToolTipService",
        "Track",
        "Transform",
        "Transform3D",
        "Transform3DCollection",
        "Transform3DGroup",
        "TransformCollection",
        "TransformConverter",
        "TransformGroup",
        "TransformedBitmap",
        "TranslateTransform",
        "TranslateTransform3D",
        "TreeView",
        "TreeViewItem",
        "Trigger",
        "TriggerAction",
        "TriggerBase",
        "TypeExtension",
        "TypeTypeConverter",
        "Typography",
        "UIElement",
        "UInt16",
        "UInt16Converter",
        "UInt32",
        "UInt32Converter",
        "UInt64",
        "UInt64Converter",
        "UShortIListConverter",
        "Underline",
        "UniformGrid",
        "Uri",
        "UriTypeConverter",
        "UserControl",
        "Validation",
        "Vector",
        "Vector3D",
        "Vector3DAnimation",
        "Vector3DAnimationBase",
        "Vector3DAnimationUsingKeyFrames",
        "Vector3DCollection",
        "Vector3DCollectionConverter",
        "Vector3DConverter",
        "Vector3DKeyFrame",
        "Vector3DKeyFrameCollection",
        "VectorAnimation",
        "VectorAnimationBase",
        "VectorAnimationUsingKeyFrames",
        "VectorCollection",
        "VectorCollectionConverter",
        "VectorConverter",
        "VectorKeyFrame",
        "VectorKeyFrameCollection",
        "VideoDrawing",
        "ViewBase",
        "Viewbox",
        "Viewport3D",
        "Viewport3DVisual",
        "VirtualizingPanel",
        "VirtualizingStackPanel",
        "Visual",
        "Visual3D",
        "VisualBrush",
        "VisualTarget",
        "WeakEventManager",
        "WhitespaceSignificantCollectionAttribute",
        "Window",
        "WmpBitmapDecoder",
        "WmpBitmapEncoder",
        "WrapPanel",
        "WriteableBitmap",
        "XamlBrushSerializer",
        "XamlInt32CollectionSerializer",
        "XamlPathDataSerializer",
        "XamlPoint3DCollectionSerializer",
        "XamlPointCollectionSerializer",
        "XamlReader",
        "XamlStyleSerializer",
        "XamlTemplateSerializer",
        "XamlVector3DCollectionSerializer",
        "XamlWriter",
        "XmlDataProvider",
        "XmlLangPropertyAttribute",
        "XmlLanguage",
        "XmlLanguageConverter",
        "XmlNamespaceMapping",
        "ZoomPercentageConverter"
    ];

    private static readonly KnownPropertyName[] PropertyNames =
    [
        default,
        new("AccessText", "Text"),
        new("BeginStoryboard", "Storyboard"),
        new("BitmapEffectGroup", "Children"),
        new("Border", "Background"),
        new("Border", "BorderBrush"),
        new("Border", "BorderThickness"),
        new("ButtonBase", "Command"),
        new("ButtonBase", "CommandParameter"),
        new("ButtonBase", "CommandTarget"),
        new("ButtonBase", "IsPressed"),
        new("ColumnDefinition", "MaxWidth"),
        new("ColumnDefinition", "MinWidth"),
        new("ColumnDefinition", "Width"),
        new("ContentControl", "Content"),
        new("ContentControl", "ContentTemplate"),
        new("ContentControl", "ContentTemplateSelector"),
        new("ContentControl", "HasContent"),
        new("ContentElement", "Focusable"),
        new("ContentPresenter", "Content"),
        new("ContentPresenter", "ContentSource"),
        new("ContentPresenter", "ContentTemplate"),
        new("ContentPresenter", "ContentTemplateSelector"),
        new("ContentPresenter", "RecognizesAccessKey"),
        new("Control", "Background"),
        new("Control", "BorderBrush"),
        new("Control", "BorderThickness"),
        new("Control", "FontFamily"),
        new("Control", "FontSize"),
        new("Control", "FontStretch"),
        new("Control", "FontStyle"),
        new("Control", "FontWeight"),
        new("Control", "Foreground"),
        new("Control", "HorizontalContentAlignment"),
        new("Control", "IsTabStop"),
        new("Control", "Padding"),
        new("Control", "TabIndex"),
        new("Control", "Template"),
        new("Control", "VerticalContentAlignment"),
        new("DockPanel", "Dock"),
        new("DockPanel", "LastChildFill"),
        new("DocumentViewerBase", "Document"),
        new("DrawingGroup", "Children"),
        new("FlowDocumentReader", "Document"),
        new("FlowDocumentScrollViewer", "Document"),
        new("FrameworkContentElement", "Style"),
        new("FrameworkElement", "FlowDirection"),
        new("FrameworkElement", "Height"),
        new("FrameworkElement", "HorizontalAlignment"),
        new("FrameworkElement", "Margin"),
        new("FrameworkElement", "MaxHeight"),
        new("FrameworkElement", "MaxWidth"),
        new("FrameworkElement", "MinHeight"),
        new("FrameworkElement", "MinWidth"),
        new("FrameworkElement", "Name"),
        new("FrameworkElement", "Style"),
        new("FrameworkElement", "VerticalAlignment"),
        new("FrameworkElement", "Width"),
        new("GeneralTransformGroup", "Children"),
        new("GeometryGroup", "Children"),
        new("GradientBrush", "GradientStops"),
        new("Grid", "Column"),
        new("Grid", "ColumnSpan"),
        new("Grid", "Row"),
        new("Grid", "RowSpan"),
        new("GridViewColumn", "Header"),
        new("HeaderedContentControl", "HasHeader"),
        new("HeaderedContentControl", "Header"),
        new("HeaderedContentControl", "HeaderTemplate"),
        new("HeaderedContentControl", "HeaderTemplateSelector"),
        new("HeaderedItemsControl", "HasHeader"),
        new("HeaderedItemsControl", "Header"),
        new("HeaderedItemsControl", "HeaderTemplate"),
        new("HeaderedItemsControl", "HeaderTemplateSelector"),
        new("Hyperlink", "NavigateUri"),
        new("Image", "Source"),
        new("Image", "Stretch"),
        new("ItemsControl", "ItemContainerStyle"),
        new("ItemsControl", "ItemContainerStyleSelector"),
        new("ItemsControl", "ItemTemplate"),
        new("ItemsControl", "ItemTemplateSelector"),
        new("ItemsControl", "ItemsPanel"),
        new("ItemsControl", "ItemsSource"),
        new("MaterialGroup", "Children"),
        new("Model3DGroup", "Children"),
        new("Page", "Content"),
        new("Panel", "Background"),
        new("Path", "Data"),
        new("PathFigure", "Segments"),
        new("PathGeometry", "Figures"),
        new("Popup", "Child"),
        new("Popup", "IsOpen"),
        new("Popup", "Placement"),
        new("Popup", "PopupAnimation"),
        new("RowDefinition", "Height"),
        new("RowDefinition", "MaxHeight"),
        new("RowDefinition", "MinHeight"),
        new("ScrollViewer", "CanContentScroll"),
        new("ScrollViewer", "HorizontalScrollBarVisibility"),
        new("ScrollViewer", "VerticalScrollBarVisibility"),
        new("Shape", "Fill"),
        new("Shape", "Stroke"),
        new("Shape", "StrokeThickness"),
        new("TextBlock", "Background"),
        new("TextBlock", "FontFamily"),
        new("TextBlock", "FontSize"),
        new("TextBlock", "FontStretch"),
        new("TextBlock", "FontStyle"),
        new("TextBlock", "FontWeight"),
        new("TextBlock", "Foreground"),
        new("TextBlock", "Text"),
        new("TextBlock", "TextDecorations"),
        new("TextBlock", "TextTrimming"),
        new("TextBlock", "TextWrapping"),
        new("TextBox", "Text"),
        new("TextElement", "Background"),
        new("TextElement", "FontFamily"),
        new("TextElement", "FontSize"),
        new("TextElement", "FontStretch"),
        new("TextElement", "FontStyle"),
        new("TextElement", "FontWeight"),
        new("TextElement", "Foreground"),
        new("TimelineGroup", "Children"),
        new("Track", "IsDirectionReversed"),
        new("Track", "Maximum"),
        new("Track", "Minimum"),
        new("Track", "Orientation"),
        new("Track", "Value"),
        new("Track", "ViewportSize"),
        new("Transform3DGroup", "Children"),
        new("TransformGroup", "Children"),
        new("UIElement", "ClipToBounds"),
        new("UIElement", "Focusable"),
        new("UIElement", "IsEnabled"),
        new("UIElement", "RenderTransform"),
        new("UIElement", "Visibility"),
        new("Viewport3D", "Children"),
        default,
        new("AdornedElementPlaceholder", "Child"),
        new("AdornerDecorator", "Child"),
        new("AnchoredBlock", "Blocks"),
        new("ArrayExtension", "Items"),
        new("BlockUIContainer", "Child"),
        new("Bold", "Inlines"),
        new("BooleanAnimationUsingKeyFrames", "KeyFrames"),
        new("Border", "Child"),
        new("BulletDecorator", "Child"),
        new("Button", "Content"),
        new("ButtonBase", "Content"),
        new("ByteAnimationUsingKeyFrames", "KeyFrames"),
        new("Canvas", "Children"),
        new("CharAnimationUsingKeyFrames", "KeyFrames"),
        new("CheckBox", "Content"),
        new("ColorAnimationUsingKeyFrames", "KeyFrames"),
        new("ComboBox", "Items"),
        new("ComboBoxItem", "Content"),
        new("ContextMenu", "Items"),
        new("ControlTemplate", "VisualTree"),
        new("DataTemplate", "VisualTree"),
        new("DataTrigger", "Setters"),
        new("DecimalAnimationUsingKeyFrames", "KeyFrames"),
        new("Decorator", "Child"),
        new("DockPanel", "Children"),
        new("DocumentViewer", "Document"),
        new("DoubleAnimationUsingKeyFrames", "KeyFrames"),
        new("EventTrigger", "Actions"),
        new("Expander", "Content"),
        new("Figure", "Blocks"),
        new("FixedDocument", "Pages"),
        new("FixedDocumentSequence", "References"),
        new("FixedPage", "Children"),
        new("Floater", "Blocks"),
        new("FlowDocument", "Blocks"),
        new("FlowDocumentPageViewer", "Document"),
        new("FrameworkTemplate", "VisualTree"),
        new("Grid", "Children"),
        new("GridView", "Columns"),
        new("GridViewColumnHeader", "Content"),
        new("GroupBox", "Content"),
        new("GroupItem", "Content"),
        new("HeaderedContentControl", "Content"),
        new("HeaderedItemsControl", "Items"),
        new("HierarchicalDataTemplate", "VisualTree"),
        new("Hyperlink", "Inlines"),
        new("InkCanvas", "Children"),
        new("InkPresenter", "Child"),
        new("InlineUIContainer", "Child"),
        new("InputScopeName", "NameValue"),
        new("Int16AnimationUsingKeyFrames", "KeyFrames"),
        new("Int32AnimationUsingKeyFrames", "KeyFrames"),
        new("Int64AnimationUsingKeyFrames", "KeyFrames"),
        new("Italic", "Inlines"),
        new("ItemsControl", "Items"),
        new("ItemsPanelTemplate", "VisualTree"),
        new("Label", "Content"),
        new("LinearGradientBrush", "GradientStops"),
        new("List", "ListItems"),
        new("ListBox", "Items"),
        new("ListBoxItem", "Content"),
        new("ListItem", "Blocks"),
        new("ListView", "Items"),
        new("ListViewItem", "Content"),
        new("MatrixAnimationUsingKeyFrames", "KeyFrames"),
        new("Menu", "Items"),
        new("MenuBase", "Items"),
        new("MenuItem", "Items"),
        new("ModelVisual3D", "Children"),
        new("MultiBinding", "Bindings"),
        new("MultiDataTrigger", "Setters"),
        new("MultiTrigger", "Setters"),
        new("ObjectAnimationUsingKeyFrames", "KeyFrames"),
        new("PageContent", "Child"),
        new("PageFunctionBase", "Content"),
        new("Panel", "Children"),
        new("Paragraph", "Inlines"),
        new("ParallelTimeline", "Children"),
        new("Point3DAnimationUsingKeyFrames", "KeyFrames"),
        new("PointAnimationUsingKeyFrames", "KeyFrames"),
        new("PriorityBinding", "Bindings"),
        new("QuaternionAnimationUsingKeyFrames", "KeyFrames"),
        new("RadialGradientBrush", "GradientStops"),
        new("RadioButton", "Content"),
        new("RectAnimationUsingKeyFrames", "KeyFrames"),
        new("RepeatButton", "Content"),
        new("RichTextBox", "Document"),
        new("Rotation3DAnimationUsingKeyFrames", "KeyFrames"),
        new("Run", "Text"),
        new("ScrollViewer", "Content"),
        new("Section", "Blocks"),
        new("Selector", "Items"),
        new("SingleAnimationUsingKeyFrames", "KeyFrames"),
        new("SizeAnimationUsingKeyFrames", "KeyFrames"),
        new("Span", "Inlines"),
        new("StackPanel", "Children"),
        new("StatusBar", "Items"),
        new("StatusBarItem", "Content"),
        new("Storyboard", "Children"),
        new("StringAnimationUsingKeyFrames", "KeyFrames"),
        new("Style", "Setters"),
        new("TabControl", "Items"),
        new("TabItem", "Content"),
        new("TabPanel", "Children"),
        new("Table", "RowGroups"),
        new("TableCell", "Blocks"),
        new("TableRow", "Cells"),
        new("TableRowGroup", "Rows"),
        new("TextBlock", "Inlines"),
        new("ThicknessAnimationUsingKeyFrames", "KeyFrames"),
        new("ToggleButton", "Content"),
        new("ToolBar", "Items"),
        new("ToolBarOverflowPanel", "Children"),
        new("ToolBarPanel", "Children"),
        new("ToolBarTray", "ToolBars"),
        new("ToolTip", "Content"),
        new("TreeView", "Items"),
        new("TreeViewItem", "Items"),
        new("Trigger", "Setters"),
        new("Underline", "Inlines"),
        new("UniformGrid", "Children"),
        new("UserControl", "Content"),
        new("Vector3DAnimationUsingKeyFrames", "KeyFrames"),
        new("VectorAnimationUsingKeyFrames", "KeyFrames"),
        new("Viewbox", "Child"),
        new("Viewport3DVisual", "Children"),
        new("VirtualizingPanel", "Children"),
        new("VirtualizingStackPanel", "Children"),
        new("Window", "Content"),
        new("WrapPanel", "Children"),
        new("XmlDataProvider", "XmlSerializer"),
        new("TextBox", "IsReadOnly"),
        new("RichTextBox", "IsReadOnly")
    ];

    public static string? GetTypeName(short id)
    {
        if (id >= 0)
        {
            return null;
        }

        var index = -(int)id;
        return index < TypeNames.Length ? TypeNames[index] : null;
    }

    public static bool TryGetProperty(
        short id,
        out string? ownerType,
        out string? name)
    {
        if (id < 0)
        {
            var index = -(int)id;
            if (index < PropertyNames.Length && PropertyNames[index].Name is not null)
            {
                ownerType = PropertyNames[index].OwnerType;
                name = PropertyNames[index].Name;
                return true;
            }
        }

        ownerType = null;
        name = null;
        return false;
    }

    private readonly record struct KnownPropertyName(string? OwnerType, string? Name);
}
